# Generated by Django 5.2.13 on 2026-05-05 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_userprofile_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='admin_licenses/'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='adminprofile',
            name='admin_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
