# Generated by Django 5.2.13 on 2026-05-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_adminprofile_license_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='auth_letter_document',
            field=models.FileField(blank=True, null=True, upload_to='admin_auth_letters/'),
        ),
        migrations.AddField(
            model_name='adminprofile',
            name='gstin_document',
            field=models.FileField(blank=True, null=True, upload_to='admin_gstin/'),
        ),
    ]
