# Generated by Django 5.2.13 on 2026-05-06 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_remove_partnerprofile_company_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='adminprofile',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20),
        ),
    ]
