# Generated by Django 5.2.13 on 2026-05-05 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_adminprofile_auth_letter_document_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partnerprofile',
            name='company_name',
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='auth_letter_document',
            field=models.FileField(blank=True, null=True, upload_to='partner_auth_letters/'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='gstin_document',
            field=models.FileField(blank=True, null=True, upload_to='partner_gstin/'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='license_document',
            field=models.FileField(blank=True, null=True, upload_to='partner_licenses/'),
        ),
        migrations.AddField(
            model_name='partnerprofile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='partnerprofile',
            name='partner_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
